Adding Home -> Participants Folder
Inter-IIT-Tech-Meet-10-0/front-end pull request #17
Opened 2021-12-13 18:33 UTC by AAYUSHAIRAN

#9

2021-12-13 18:41 UTC, AAYUSHAIRAN commented
@parth-paradkar  don't merge,
yet to add a responsive part 
Will add by tomorrow

2021-12-21 05:56 UTC, parth-paradkar requested changes
Shift inline styles to CSS file

2021-12-21 05:56 UTC, parth-paradkar commented on src/components/Home/components/participants/participants.js
> +        }}
Inline style

2021-12-21 05:56 UTC, parth-paradkar commented on src/components/Home/components/participants/participants.js
> +        }}
Inline styles

2021-12-21 14:29 UTC, parth-paradkar approved these changes

2021-12-21 14:30 UTC, merged